blank_issues_enabled: false
contact_links:
    - name: Documentation
      url: https://appkit.coutts.io/packages/ui/docs
      about: View the documentation
      
    - name: Community
      url: https://appkit.coutts.io/packages/ui/community
      about: Ask the community for help
